In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
df = pd.read_csv('spam.csv')

In [4]:
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [6]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.Message,df.Category,test_size = 0.3)

In [15]:
x_train

4843        Awesome, that gonna be soon or later tonight?
4398                               When did dad get back.
2010    I can't keep going through this. It was never ...
2816    Some are lasting as much as 2 hours. You might...
394     Yes i think so. I am in office but my lap is i...
                              ...
2201    Haha... can... But i'm having dinner with my c...
3137    Can you let me know details of fri when u find...
536     Good afternoon, my love! How goes that day ? I...
2931                    Wat's my dear doing? Sleeping ah?
1555                      Yeah we do totes. When u wanna?
Name: Message, Length: 3900, dtype: object

In [16]:
x_train.values

array(['Awesome, that gonna be soon or later tonight?',
       'When did dad get back.',
       "I can't keep going through this. It was never my intention to run you out, but if you choose to do that rather than keep the room clean so *I* don't have to say no to visitors, then maybe that's the best choice. Yes, I wanted you to be embarassed, so maybe you'd feel for once how I feel when i have a friend who wants to drop buy and i have to say no, as happened this morning. I've tried everything. I don't know what else to do.",
       ...,
       'Good afternoon, my love! How goes that day ? I hope maybe you got some leads on a job. I think of you, boytoy and send you a passionate kiss from across the sea',
       "Wat's my dear doing? Sleeping ah?",
       'Yeah we do totes. When u wanna?'], dtype=object)

In [29]:
x_test

513                               Lol ok your forgiven :)
4134    FreeMsg Today's the day if you are ready! I'm ...
2117               It's that time of the week again, ryan
4461    This is wishing you a great day. Moji told me ...
2891    Shuhui has bought ron's present it's a swatch ...
                              ...
2682                          I'm on da bus going home...
100     Please don't text me anymore. I have nothing e...
4736                 Oh k:)after that placement there ah?
3340    Babe !!!! I LOVE YOU !!!! *covers your face in...
3504     Free any day but i finish at 6 on mon n thurs...
Name: Message, Length: 1672, dtype: object

# x_train bag_of_words

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
fe = CountVectorizer()
x_train_cv = fe.fit_transform(x_train.values)

In [18]:
x_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [19]:
x_train_cv.shape

(3900, 7174)

In [23]:
fe.get_feature_names_out()

array(['00', '000', '000pes', ..., 'zyada', 'èn', 'ú1'], dtype=object)

In [31]:
pd.DataFrame(data = x_train_cv.toarray() , columns = fe.get_feature_names_out())

,00,000,000pes,008704050406,0089,01223585236,01223585334,0125698789,02,0207,...,zebra,zed,zhong,zindgi,zoe,zogtorius,zoom,zyada,èn,ú1
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3896,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3897,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3898,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3899,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# naive bayes model

In [28]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train_cv,y_train)

MultinomialNB()

# x_test bag_of_words

In [32]:
x_test_cv = fe.transform(x_test)

In [33]:
x_test_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [34]:
x_test_cv.shape

(1672, 7174)

In [35]:
fe.get_feature_names_out(x_test)

array(['00', '000', '000pes', ..., 'zyada', 'èn', 'ú1'], dtype=object)

In [36]:
pd.DataFrame(data = x_test_cv.toarray(),columns = fe.get_feature_names_out())

,00,000,000pes,008704050406,0089,01223585236,01223585334,0125698789,02,0207,...,zebra,zed,zhong,zindgi,zoe,zogtorius,zoom,zyada,èn,ú1
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1667,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1668,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1669,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1670,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1671,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [39]:
model.score(x_test_cv,y_test)

0.9796650717703349

In [40]:
y_test

513      ham
4134    spam
2117     ham
4461     ham
2891     ham
        ...
2682     ham
100      ham
4736     ham
3340     ham
3504     ham
Name: Category, Length: 1672, dtype: object

In [38]:
model.predict(x_test_cv)

array(['ham', 'spam', 'ham', ..., 'ham', 'ham', 'ham'], dtype='<U4')